/**
 * Keywords e expressões para detecção de sentimento/treta em pt-BR.
 *
 * Centraliza todas as palavras usadas pelo SentimentService.
 * Categorias:
 *   - HEAVY: palavrões e ofensas pesadas (+3 pontos)
 *   - MEDIUM: provocações e ofensas moderadas (+2 pontos)
 *   - LIGHT: expressões de frustração e irritação (+1 ponto)
 *
 * Inclui variações com e sem acento para capturar escrita informal,
 * além de abreviações comuns de WhatsApp.
 *
 * Fontes: Wikipedia (palavrões pt-BR), aprenderpalavras.com,
 * dunossauro/chat-detox, youswear.com, rioandlearn.com
 */

/** Palavrões e ofensas pesadas — indicam briga real. */
export const HEAVY_KEYWORDS: string[] = [
  // Palavrões clássicos e variações
  'filho da puta',
  'filha da puta',
  'filho da mãe',
  'filho da mae',
  'fdp',
  'vai se foder',
  'se foder',
  'se fuder',
  'vai tomar no cu',
  'tomar no cu',
  'pau no cu',
  'puta que pariu',
  'na puta que pariu',
  'vai pra puta que pariu',
  'pqp',
  'vsf',
  'vsfd',
  'vtmnc',
  'vtnc',
  'tnc',
  'pnc',
  'foda-se',
  'fodase',
  'foda se',
  'foda',
  'fudeu',
  'fudido',
  'fudida',
  'nem fodendo',
  'vai pro inferno',
  'vai pro caralho',
  'vai a merda',
  'vai à merda',
  'vai pra pqp',
  'caralho',
  'krl',
  'puta merda',
  // Ofensas pesadas a pessoas
  'arrombado',
  'arrombada',
  'corno',
  'corna',
  'cornudo',
  'chifrudo',
  'vagabundo',
  'vagabunda',
  'desgraçado',
  'desgracado',
  'desgraçada',
  'desgracada',
  'desgraça',
  'desgraca',
  'piranha',
  'vadia',
  'safado',
  'safada',
  'cuzão',
  'cuzao',
  'cuzona',
  'escroto',
  'escrota',
  'miserável',
  'miseravel',
  'canalha',
  'crápula',
  'crapula',
  'verme',
  'parasita',
  'viado',
  'veado',
  'bicha',
  'boiola',
];

/** Provocações e ofensas moderadas — discussão acalorada. */
export const MEDIUM_KEYWORDS: string[] = [
  // Xingamentos à inteligência
  'idiota',
  'imbecil',
  'burro',
  'burra',
  'estúpido',
  'estupido',
  'estúpida',
  'estupida',
  'ignorante',
  'retardado',
  'retardada',
  'débil mental',
  'debil mental',
  'doente mental',
  'energúmeno',
  'energumeno',
  'panaca',
  'paspalho',
  'anta',
  'jumento',
  'jumenta',
  'asno',
  'animal',
  'cavalo',
  'besta',
  'bestalhão',
  'bestalhao',
  'lesado',
  'lesada',
  'lerdo',
  'lerda',
  'tapado',
  'tapada',
  'demente',
  'lunático',
  'lunatico',
  // Xingamentos de caráter
  'babaca',
  'babacão',
  'babacona',
  'otário',
  'otario',
  'otária',
  'otaria',
  'cretino',
  'cretina',
  'palhaço',
  'palhaco',
  'palhaçada',
  'palhacada',
  'mentiroso',
  'mentirosa',
  'mentira',
  'ridículo',
  'ridiculo',
  'ridícula',
  'ridicula',
  'patético',
  'patetico',
  'patética',
  'patetica',
  'nojento',
  'nojenta',
  'tosco',
  'tosca',
  'arrogante',
  'prepotente',
  'insuportável',
  'insuportavel',
  'descarado',
  'descarada',
  'hipócrita',
  'hipocrita',
  'dissimulado',
  'dissimulada',
  'pilantra',
  'embusteiro',
  'embusteira',
  'falso',
  'falsa',
  'cobra',
  'traíra',
  'traira',
  // Ofensas diretas
  'lixo',
  'lixo humano',
  'vergonha',
  'nojo',
  'podre',
  'maldito',
  'maldita',
  'praga',
  'peste',
  'covarde',
  'frouxo',
  'frouxa',
  'infeliz',
  // Palavrões moderados
  'merda',
  'porra',
  'droga',
  'bosta',
  'cacete',
  'kct',
  'porcaria',
  'putaria',
  // Provocações e vacilação
  'vacilão',
  'vacilao',
  'vacilona',
  'vacilo',
  'sacana',
  'sacanagem',
  'safadeza',
  'mané',
  'mane',
  'trouxa',
  'maluco',
  'maluca',
  'doente',
  'perturbado',
  'perturbada',
  'desequilibrado',
  'desequilibrada',
  // Comportamento
  'folgado',
  'folgada',
  'abusado',
  'abusada',
  'enxerido',
  'enxerida',
  'intrometido',
  'intrometida',
  'metido',
  'metida',
  'mala',
  'chato',
  'chata',
  'inútil',
  'inutil',
  'incompetente',
  'negligente',
  'irresponsável',
  'irresponsavel',
  'imprestável',
  'imprestavel',
  'mal educado',
  'grosso',
  'grossa',
  'grosseiro',
  'grosseira',
  'sem vergonha',
  'cara de pau',
  'sem caráter',
  'sem carater',
  'ordinário',
  'ordinario',
  'ordinária',
  'ordinaria',
  'grotesco',
  'grotesca',
  'medíocre',
  'mediocre',
  'puxa-saco',
  'puxa saco',
  'interesseiro',
  'interesseira',
  'aproveitador',
  'aproveitadora',
  'caga regra',
  // Substantivos derivados
  'imbecilidade',
  'estupidez',
  'idiotice',
  'absurdo',
  'treteiro',
  'treteira',
];

/** Expressões de frustração e irritação — esquentando. */
export const LIGHT_KEYWORDS: string[] = [
  // Expressões de raiva/frustração
  'não acredito',
  'nao acredito',
  'num acredito',
  'que ódio',
  'que odio',
  'que raiva',
  'que nojo',
  'que lixo',
  'que merda',
  'que droga',
  'que porra',
  'que bosta',
  'que saco',
  'inferno',
  // Expressões de espanto/incredulidade
  'tá maluco',
  'ta maluco',
  'tá louco',
  'ta louco',
  'tá maluca',
  'ta maluca',
  'tá louca',
  'ta louca',
  'cê é doido',
  'ce e doido',
  'cê é doida',
  'ce e doida',
  'tá de brincadeira',
  'ta de brincadeira',
  'tá de sacanagem',
  'ta de sacanagem',
  'tá de palhaçada',
  'ta de palhacada',
  'tá de zoeira',
  'ta de zoeira',
  'sério isso',
  'serio isso',
  // Expressões de cansaço/saturação
  'não aguento mais',
  'nao aguento mais',
  'cansei',
  'cansei dessa merda',
  'to de saco cheio',
  'tô de saco cheio',
  'encheu o saco',
  'enche o saco',
  'saco cheio',
  'to puto',
  'tô puto',
  'to puta',
  'tô puta',
  'puto da vida',
  'puta da vida',
  'dane-se',
  'dane se',
  'porra nenhuma',
  'caguei',
  // Mandando calar/sair
  'cala a boca',
  'sai fora',
  'sai daqui',
  'some daqui',
  'vai se',
  'vai tomar',
  'não fode',
  'nao fode',
  'não enche',
  'nao enche',
  'para com isso',
  'para de falar besteira',
  'chega',
  // Apelos e interjeições
  'pelo amor de deus',
  'pelo amor',
  'pelamor',
  'plmds',
  'meu deus',
  'mds',
  'mano do céu',
  'mano do ceu',
  'cruz credo',
  'misericórdia',
  'misericordia',
  'oxe',
  'eita',
  'aff',
  'pff',
  'tsc',
  // Provocações leves e reclamações
  'fala sério',
  'fala serio',
  'na moral',
  'nmrl',
  'sem noção',
  'sem nocao',
  'que absurdo',
  'besteira',
  'bobagem',
  'piada',
  'viaja não',
  'viaja nao',
  'frescura',
  'fresco',
  'fresca',
  'para de frescura',
  'mimimi',
  'mimado',
  'mimada',
  'mimizento',
  'chorume',
  'chorão',
  'chorao',
  'chorona',
  'textão',
  'textao',
  // Acusações de provocação
  'tá querendo o quê',
  'ta querendo o que',
  'tá pedindo',
  'ta pedindo',
  'quer briga',
  'procurando treta',
  'vai arrumar o que fazer',
  'arruma o que fazer',
  // Termos de discussão
  'treta',
  'zueira',
  'zoeira',
  'zuado',
  'zoado',
  'papo reto',
  'perreco',
  'perrequeiro',
  'caô',
  'cao',
  'conversinha',
  'papinho',
  'migué',
  'migue',
  'enrolação',
  'enrolacao',
  'sem graça',
  'sem graca',
  'olha o nível',
  'olha o nivel',
  'baixo nível',
  'baixo nivel',
  'lacração',
  'lacracao',
  'militância',
  'militancia',
  'problematizar',
];

/** Todas as keywords agrupadas com seus pesos. */
export const WEIGHTED_KEYWORDS: Array<{ words: string[]; weight: number }> = [
  { words: HEAVY_KEYWORDS, weight: 3 },
  { words: MEDIUM_KEYWORDS, weight: 2 },
  { words: LIGHT_KEYWORDS, weight: 1 },
];
